version: '3'

services:
  portal:
    restart: always
    build:
      context: .
      args:
        PIP_REQUIREMENTS: requirements-dev.txt
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    entrypoint: python3
    command: /opt/app/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/opt/app
    environment:
      stage: local
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_DEFAULT_REGION: ${AWS_REGION}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  portal-test:
    build:
      context: .
      args:
        PIP_REQUIREMENTS: requirements-dev.txt
    volumes:
      - .:/code
    entrypoint: ''
    command: coverage run --source='.' manage.py test -v 2
    volumes:
      - ./:/opt/app
    environment:
      stage: test
