version: '3'

services:
  portal:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    entrypoint: python3
    command: /opt/app/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/opt/app
    environment:
      stage: local
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_DEFAULT_REGION: ${AWS_REGION}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      POSTMAN_MOCK_SERVER_API_KEY_MET_SERVICE: ${POSTMAN_MOCK_SERVER_API_KEY_MET_SERVICE}
    networks:
      default:
          aliases:
              - portal_1
  portal-test:
    build:
      context: .
      args:
        PIP_REQUIREMENTS: requirements-test.txt
    volumes:
      - ./:/opt/app
    entrypoint: ''
    command: >
      sh -c "coverage run --source='.' manage.py test -v 2 &&
             coverage report"
    environment:
      stage: test

networks:
  default:
    external:
      name: portal_network
