version: 2
jobs:
  build:
    working_directory: ~/circleci
    docker:
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: requirements_1-{{ .Branch }}-{{ checksum "requirements-test.txt" }}
      - run:
          name: Install Python dependencies in a virtual env
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-test.txt
      - save_cache:
          key: requirements_1-{{ .Branch }}-{{ checksum "requirements-test.txt" }}
          paths:
            - "venv"
      - run:
          name: run tests and generate coverage report
          command: |
            . venv/bin/activate
            python manage.py test
            coverage run --omit='/home/circleci/circleci/venv/*' manage.py test -v 2 &&
            coverage html -d artifacts
      - store_artifacts:
          path: artifacts
          destination: cov
